#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-ash
Version  : 1.0.15
Release  : 11
URL      : https://cran.r-project.org/src/contrib/ash_1.0-15.tar.gz
Source0  : https://cran.r-project.org/src/contrib/ash_1.0-15.tar.gz
Summary  : David Scott's ASH Routines
Group    : Development/Tools
License  : GPL-2.0+
Requires: R-ash-lib = %{version}-%{release}
BuildRequires : buildreq-R

%description
------------------------------------------------------------------
Albrecht Gebhardt           email: albrecht.gebhardt@uni-klu.ac.at
Institut fuer Mathematik    Tel. : (++43 463) 2700/837
Universitaet Klagenfurt     Fax  : (++43 463) 2700/834
Villacher Str. 161
A-9020 Klagenfurt, Austria
------------------------------------------------------------------

%package lib
Summary: lib components for the R-ash package.
Group: Libraries

%description lib
lib components for the R-ash package.


%prep
%setup -q -c -n ash

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1552915349

%install
export SOURCE_DATE_EPOCH=1552915349
rm -rf %{buildroot}
export LANG=C
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library ash
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library ash
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library ash
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc  ash || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/ash/DESCRIPTION
/usr/lib64/R/library/ash/INDEX
/usr/lib64/R/library/ash/Meta/Rd.rds
/usr/lib64/R/library/ash/Meta/features.rds
/usr/lib64/R/library/ash/Meta/hsearch.rds
/usr/lib64/R/library/ash/Meta/links.rds
/usr/lib64/R/library/ash/Meta/nsInfo.rds
/usr/lib64/R/library/ash/Meta/package.rds
/usr/lib64/R/library/ash/NAMESPACE
/usr/lib64/R/library/ash/R/ash
/usr/lib64/R/library/ash/R/ash.rdb
/usr/lib64/R/library/ash/R/ash.rdx
/usr/lib64/R/library/ash/help/AnIndex
/usr/lib64/R/library/ash/help/aliases.rds
/usr/lib64/R/library/ash/help/ash.rdb
/usr/lib64/R/library/ash/help/ash.rdx
/usr/lib64/R/library/ash/help/paths.rds
/usr/lib64/R/library/ash/html/00Index.html
/usr/lib64/R/library/ash/html/R.css

%files lib
%defattr(-,root,root,-)
/usr/lib64/R/library/ash/libs/ash.so
/usr/lib64/R/library/ash/libs/ash.so.avx2
/usr/lib64/R/library/ash/libs/ash.so.avx512
